//! WASM indexer runtime using wasmtime.
//!
//! Dual-engine design matching metashrew-runtime:
//! - **Sync engine**: for `run_block()` (called from rayon threads)
//! - **Async engine**: for `call_view()` with fuel-based cooperative yielding

use crate::storage::IndexerStorage;
use prost::Message;
use std::collections::HashMap;
use std::sync::Arc;
use wasmtime::*;

/// Protobuf message for KeyValueFlush (generated by prost).
mod proto {
    include!(concat!(env!("OUT_DIR"), "/metashrew.rs"));
}

/// Host state threaded through the wasmtime `Store`.
pub struct WasmState {
    pub input_data: Vec<u8>,
    pub pending_flush: Option<Vec<(Vec<u8>, Vec<u8>)>>,
    pub storage: Arc<IndexerStorage>,
    pub had_failure: bool,
    pub completed: bool,
    pub label: String,
    pub view_mode: bool,
    pub limits: StoreLimits,
    /// Write-through cache: __flush writes are staged here so subsequent
    /// __get/__get_len calls within the same _start() can read them back.
    /// Matches qubitcoin-indexer-web's write_cache behavior.
    pub write_cache: HashMap<Vec<u8>, Vec<u8>>,
}

/// Build the deterministic engine config matching metashrew-runtime.
fn base_config() -> Config {
    let mut config = Config::new();
    config.wasm_bulk_memory(true);
    config.wasm_multi_value(true);
    config.wasm_reference_types(true);
    config.wasm_simd(true);
    config.cranelift_nan_canonicalization(true);
    config.relaxed_simd_deterministic(true);
    config.memory_reservation(0x100000000); // 4GB
    config.memory_guard_size(0x10000); // 64KB
    // CoW memory init: reuse OS-level copy-on-write pages instead of
    // zeroing memory for each new instance. Eliminates ~12% CPU from
    // page fault handling (clear_page_erms, do_anonymous_page).
    // Must match metashrew-runtime: false ensures deterministic memory
    // initialization. With true, stale memory pages from previous
    // instances can leak, causing non-deterministic WASM execution.
    config.memory_init_cow(true);
    config
}

fn new_state(
    input_data: Vec<u8>,
    storage: Arc<IndexerStorage>,
    label: &str,
    view_mode: bool,
) -> WasmState {
    WasmState {
        input_data,
        pending_flush: None,
        storage,
        had_failure: false,
        completed: false,
        label: label.to_string(),
        view_mode,
        limits: StoreLimitsBuilder::new()
            .memories(usize::MAX)
            .tables(usize::MAX)
            .instances(usize::MAX)
            .build(),
        write_cache: HashMap::new(),
    }
}

/// Ensure WASM memory can grow on demand.
///
/// Unlike metashrew's single-indexer setup which pre-allocates 4GB,
/// we run multiple indexers so we let memory grow on demand via
/// wasmtime's StoreLimits (set to usize::MAX). The static_memory
/// config ensures the address space is reserved without committing
/// physical pages.
fn prepare_memory(_instance: &Instance, _store: &mut Store<WasmState>) {
    // Memory grows on demand via StoreLimits. No pre-allocation needed
    // since memory_reservation(4GB) reserves virtual address space
    // and memory_init_cow(false) ensures deterministic initial state.
}

/// A compiled WASM indexer runtime with dual engines.
pub struct WasmIndexerRuntime {
    /// Sync engine for block processing.
    engine: Engine,
    module: Module,
    /// Async engine with fuel for view functions.
    async_engine: Engine,
    async_module: Module,
}

impl WasmIndexerRuntime {
    /// Compile a WASM module from bytes.
    pub fn new(wasm_bytes: &[u8]) -> Result<Self, String> {
        // Async engine for block processing (matching metashrew/rockshrew).
        // async_support is required because the host functions use
        // func_wrap_async and _start is called with call_async.
        let mut config = base_config();
        config.async_support(true);
        let engine = Engine::new(&config).map_err(|e| format!("wasmtime engine: {}", e))?;
        let module =
            Module::new(&engine, wasm_bytes).map_err(|e| format!("wasmtime compile: {}", e))?;

        // Async engine for view functions (no fuel — wasmi needs uninterrupted execution).
        let mut async_config = base_config();
        async_config.async_support(true);
        let async_engine =
            Engine::new(&async_config).map_err(|e| format!("async wasmtime engine: {}", e))?;
        let async_module = Module::new(&async_engine, wasm_bytes)
            .map_err(|e| format!("async wasmtime compile: {}", e))?;

        Ok(WasmIndexerRuntime {
            engine,
            module,
            async_engine,
            async_module,
        })
    }

    /// Run `_start()` for block processing using async execution.
    ///
    /// Uses call_async matching metashrew-runtime's execution model.
    /// This is critical because the alkanes WASM's embedded wasmi interpreter
    /// needs the async fiber stack for deeply recursive extcall operations.
    pub fn run_block(
        &self,
        input_data: Vec<u8>,
        storage: Arc<IndexerStorage>,
        label: &str,
    ) -> Result<Vec<(Vec<u8>, Vec<u8>)>, String> {
        let state = new_state(input_data, storage, label, false);
        let mut store = Store::new(&self.engine, state);
        store.limiter(|s| &mut s.limits);

        // Use async instantiation + execution (matching metashrew).
        let instance = self.instantiate_async_block(&mut store)?;
        prepare_memory(&instance, &mut store);

        let start_fn = instance
            .get_typed_func::<(), ()>(&mut store, "_start")
            .map_err(|e| format!("missing _start: {}", e))?;

        // Use call_async via a one-shot tokio runtime.
        // The async fiber gives the WASM more stack space for
        // deeply nested extcalls.
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| format!("tokio runtime: {}", e))?;

        rt.block_on(async {
            start_fn
                .call_async(&mut store, ())
                .await
                .map_err(|e| format!("_start failed: {}", e))
        })?;

        let state = store.into_data();
        if state.had_failure {
            return Err("WASM module aborted".into());
        }
        if !state.completed {
            return Err("WASM module did not call __flush".into());
        }

        Ok(state.pending_flush.unwrap_or_default())
    }

    /// Call a view function asynchronously with fuel-based cooperative yielding.
    ///
    /// Uses the async engine so long-running view queries yield back to the
    /// tokio runtime periodically, improving concurrency.
    pub async fn call_view_async(
        &self,
        fn_name: &str,
        input_data: Vec<u8>,
        storage: Arc<IndexerStorage>,
        label: &str,
    ) -> Result<Vec<u8>, String> {
        // Metashrew ABI: view functions also expect [height_le32 ++ payload].
        // Use the current tip height from storage.
        let tip_height = storage.tip_height();
        let mut prefixed_input = Vec::with_capacity(4 + input_data.len());
        prefixed_input.extend_from_slice(&tip_height.to_le_bytes());
        prefixed_input.extend_from_slice(&input_data);
        let state = new_state(prefixed_input, storage, label, true);
        let mut store = Store::new(&self.async_engine, state);
        store.limiter(|s| &mut s.limits);

        // Fuel disabled — the internal wasmi interpreter needs uninterrupted
        // execution for deeply nested extcalls. Fuel-based yielding can cause
        // "unexpected end of file" errors when wasmi is mid-parse.
        //
        // store.set_fuel(u64::MAX).ok();
        // store.fuel_async_yield_interval(Some(10000)).ok();

        let instance = self.instantiate_async(&mut store).await?;
        prepare_memory(&instance, &mut store);

        let view_fn = instance
            .get_typed_func::<(), i32>(&mut store, fn_name)
            .map_err(|e| format!("missing view fn '{}': {}", fn_name, e))?;

        let result_ptr = view_fn
            .call_async(&mut store, ())
            .await
            .map_err(|e| format!("view fn '{}' failed: {}", fn_name, e))?;

        let memory = instance
            .get_memory(&mut store, "memory")
            .ok_or("no memory export")?;

        read_arraybuffer(&store, &memory, result_ptr)
    }

    /// Synchronous view call (for use from non-async contexts like tests).
    pub fn call_view(
        &self,
        fn_name: &str,
        input_data: Vec<u8>,
        storage: Arc<IndexerStorage>,
        label: &str,
    ) -> Result<Vec<u8>, String> {
        // Metashrew ABI: view functions expect [height_le32 ++ payload].
        let tip_height = storage.tip_height();
        let mut prefixed_input = Vec::with_capacity(4 + input_data.len());
        prefixed_input.extend_from_slice(&tip_height.to_le_bytes());
        prefixed_input.extend_from_slice(&input_data);
        let state = new_state(prefixed_input, storage, label, true);
        let mut store = Store::new(&self.engine, state);
        store.limiter(|s| &mut s.limits);

        let instance = self.instantiate_sync(&mut store)?;
        prepare_memory(&instance, &mut store);

        let view_fn = instance
            .get_typed_func::<(), i32>(&mut store, fn_name)
            .map_err(|e| format!("missing view fn '{}': {}", fn_name, e))?;

        let result_ptr = view_fn
            .call(&mut store, ())
            .map_err(|e| format!("view fn '{}' failed: {}", fn_name, e))?;

        let memory = instance
            .get_memory(&mut store, "memory")
            .ok_or("no memory export")?;

        read_arraybuffer(&store, &memory, result_ptr)
    }

    /// Link host functions and instantiate synchronously.
    fn instantiate_sync(&self, store: &mut Store<WasmState>) -> Result<Instance, String> {
        let mut linker = Linker::new(&self.engine);
        link_host_functions_sync(&mut linker)?;
        linker
            .define_unknown_imports_as_traps(&self.module)
            .map_err(|e| format!("define unknown imports: {}", e))?;
        linker
            .instantiate(&mut *store, &self.module)
            .map_err(|e| format!("wasmtime instantiate: {}", e))
    }

    /// Link async host functions and instantiate for block processing.
    /// Uses the same engine (with async_support) as block processing.
    fn instantiate_async_block(&self, store: &mut Store<WasmState>) -> Result<Instance, String> {
        let mut linker = Linker::new(&self.engine);
        link_host_functions_async(&mut linker)?;
        linker
            .define_unknown_imports_as_traps(&self.module)
            .map_err(|e| format!("define unknown imports: {}", e))?;
        // Use blocking instantiate since we're in a sync context
        // (the async comes from call_async on _start)
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .map_err(|e| format!("tokio runtime: {}", e))?;
        rt.block_on(async {
            linker
                .instantiate_async(&mut *store, &self.module)
                .await
                .map_err(|e| format!("wasmtime instantiate_async: {}", e))
        })
    }

    /// Link host functions and instantiate asynchronously.
    async fn instantiate_async(
        &self,
        store: &mut Store<WasmState>,
    ) -> Result<Instance, String> {
        let mut linker = Linker::new(&self.async_engine);
        link_host_functions_async(&mut linker)?;
        linker
            .define_unknown_imports_as_traps(&self.async_module)
            .map_err(|e| format!("define unknown imports: {}", e))?;
        linker
            .instantiate_async(&mut *store, &self.async_module)
            .await
            .map_err(|e| format!("wasmtime instantiate_async: {}", e))
    }
}

// ---------------------------------------------------------------------------
// Sync host function linking (for block processing)
// ---------------------------------------------------------------------------

fn link_host_functions_sync(linker: &mut Linker<WasmState>) -> Result<(), String> {
    linker
        .func_wrap("env", "__host_len", |caller: Caller<'_, WasmState>| -> i32 {
            caller.data().input_data.len() as i32
        })
        .map_err(|e| format!("link __host_len: {}", e))?;

    linker
        .func_wrap(
            "env",
            "__load_input",
            |mut caller: Caller<'_, WasmState>, ptr: i32| {
                let data = caller.data().input_data.clone();
                let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                memory.write(&mut caller, ptr as usize, &data).ok();
            },
        )
        .map_err(|e| format!("link __load_input: {}", e))?;

    linker
        .func_wrap(
            "env",
            "__get_len",
            |mut caller: Caller<'_, WasmState>, key_ptr: i32| -> i32 {
                let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                let key = match read_arraybuffer(&caller, &memory, key_ptr) {
                    Ok(k) => k,
                    Err(_) => return 0,
                };
                // Check write_cache first (same-block __flush writes)
                if let Some(v) = caller.data().write_cache.get(&key) {
                    return v.len() as i32;
                }
                // Raw get: the WASM module manages its own append-only
                // key layout (metashrew length_key/index_key pattern).
                // We store KV pairs from __flush directly via write_batch,
                // so raw get() is correct here.
                match caller.data().storage.get(&key) {
                    Some(v) => v.len() as i32,
                    None => 0,
                }
            },
        )
        .map_err(|e| format!("link __get_len: {}", e))?;

    linker
        .func_wrap(
            "env",
            "__get",
            |mut caller: Caller<'_, WasmState>, key_ptr: i32, value_ptr: i32| {
                let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                let key = match read_arraybuffer(&caller, &memory, key_ptr) {
                    Ok(k) => k,
                    Err(_) => return,
                };
                // Check write_cache first (same-block __flush writes)
                let value = caller
                    .data()
                    .write_cache
                    .get(&key)
                    .cloned()
                    .or_else(|| {
                        // Raw get: WASM manages its own key layout.
                        caller.data().storage.get(&key)
                    });
                if let Some(value) = value {
                    memory.write(&mut caller, value_ptr as usize, &value).ok();
                }
            },
        )
        .map_err(|e| format!("link __get: {}", e))?;

    linker
        .func_wrap(
            "env",
            "__flush",
            |mut caller: Caller<'_, WasmState>, data_ptr: i32| {
                flush_handler(&mut caller, data_ptr);
            },
        )
        .map_err(|e| format!("link __flush: {}", e))?;

    linker
        .func_wrap(
            "env",
            "__log",
            |mut caller: Caller<'_, WasmState>, ptr: i32| {
                log_handler(&mut caller, ptr);
            },
        )
        .map_err(|e| format!("link __log: {}", e))?;

    linker
        .func_wrap(
            "env",
            "abort",
            |mut caller: Caller<'_, WasmState>, msg_ptr: i32, _file: i32, line: i32, col: i32| {
                abort_handler(&mut caller, msg_ptr, line, col);
            },
        )
        .map_err(|e| format!("link abort: {}", e))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Async host function linking (for view functions with fuel yielding)
// ---------------------------------------------------------------------------

fn link_host_functions_async(linker: &mut Linker<WasmState>) -> Result<(), String> {
    linker
        .func_wrap_async(
            "env",
            "__host_len",
            |caller: Caller<'_, WasmState>, _: ()| {
                Box::new(async move { caller.data().input_data.len() as i32 })
            },
        )
        .map_err(|e| format!("link async __host_len: {}", e))?;

    linker
        .func_wrap_async(
            "env",
            "__load_input",
            |mut caller: Caller<'_, WasmState>, (ptr,): (i32,)| {
                Box::new(async move {
                    let data = caller.data().input_data.clone();
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    memory
                        .write(&mut caller, ptr as usize, &data)
                        .expect("FATAL: __load_input memory write failed");
                })
            },
        )
        .map_err(|e| format!("link async __load_input: {}", e))?;

    linker
        .func_wrap_async(
            "env",
            "__get_len",
            |mut caller: Caller<'_, WasmState>, (key_ptr,): (i32,)| {
                Box::new(async move {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    let key = match read_arraybuffer(&caller, &memory, key_ptr) {
                        Ok(k) => k,
                        Err(_) => return 0i32,
                    };
                    if let Some(v) = caller.data().write_cache.get(&key) {
                        return v.len() as i32;
                    }
                    // Raw get: the WASM module manages its own storage format.
                    match caller.data().storage.get(&key) {
                        Some(v) => v.len() as i32,
                        None => 0,
                    }
                })
            },
        )
        .map_err(|e| format!("link async __get_len: {}", e))?;

    linker
        .func_wrap_async(
            "env",
            "__get",
            |mut caller: Caller<'_, WasmState>, (key_ptr, value_ptr): (i32, i32)| {
                Box::new(async move {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    let key = match read_arraybuffer(&caller, &memory, key_ptr) {
                        Ok(k) => k,
                        Err(_) => return,
                    };
                    let value = caller
                        .data()
                        .write_cache
                        .get(&key)
                        .cloned()
                        .or_else(|| {
                            caller.data().storage.get(&key)
                        });
                    if let Some(ref value) = value {
                        if value.len() > 10000 && caller.data().view_mode {
                            tracing::info!(
                                key_len = key.len(),
                                val_len = value.len(),
                                first4 = %format!("{:02x}{:02x}{:02x}{:02x}", value[0], value[1], value[2], value[3]),
                                "async __get large read (view mode)"
                            );
                        }
                        memory
                            .write(&mut caller, value_ptr as usize, value)
                            .expect("FATAL: __get memory write failed");
                    }
                })
            },
        )
        .map_err(|e| format!("link async __get: {}", e))?;

    linker
        .func_wrap_async(
            "env",
            "__flush",
            |mut caller: Caller<'_, WasmState>, (data_ptr,): (i32,)| {
                Box::new(async move {
                    flush_handler(&mut caller, data_ptr);
                })
            },
        )
        .map_err(|e| format!("link async __flush: {}", e))?;

    linker
        .func_wrap_async(
            "env",
            "__log",
            |mut caller: Caller<'_, WasmState>, (ptr,): (i32,)| {
                Box::new(async move {
                    log_handler(&mut caller, ptr);
                })
            },
        )
        .map_err(|e| format!("link async __log: {}", e))?;

    linker
        .func_wrap_async(
            "env",
            "abort",
            |mut caller: Caller<'_, WasmState>, (msg_ptr, _file, line, col): (i32, i32, i32, i32)| {
                Box::new(async move {
                    abort_handler(&mut caller, msg_ptr, line, col);
                })
            },
        )
        .map_err(|e| format!("link async abort: {}", e))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Shared host function implementations
// ---------------------------------------------------------------------------

fn flush_handler(caller: &mut Caller<'_, WasmState>, data_ptr: i32) {
    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
    let data = match read_arraybuffer(&*caller, &memory, data_ptr) {
        Ok(d) => d,
        Err(e) => {
            tracing::error!(error = %e, "failed to read __flush data");
            caller.data_mut().had_failure = true;
            return;
        }
    };

    let flush_msg = match proto::KeyValueFlush::decode(data.as_slice()) {
        Ok(m) => m,
        Err(e) => {
            tracing::error!(error = %e, "failed to decode KeyValueFlush");
            caller.data_mut().had_failure = true;
            return;
        }
    };

    let mut pairs = Vec::new();
    let list = &flush_msg.list;
    let mut i = 0;
    while i + 1 < list.len() {
        pairs.push((list[i].to_vec(), list[i + 1].to_vec()));
        i += 2;
    }

    // Stage flush writes in write_cache so subsequent __get/__get_len
    // calls within the same _start() can read them back. This matches
    // qubitcoin-indexer-web's write_cache behavior.
    for (k, v) in &pairs {
        caller.data_mut().write_cache.insert(k.clone(), v.clone());
    }

    // Do NOT write to RocksDB here — matching qubitcoin-indexer-web which
    // says "storage is not modified (the caller applies pending_flush)".
    // The write_cache handles same-block read-after-write visibility.
    // The caller (run_indexer_block) writes to storage after _start() returns.

    // Accumulate pairs across multiple __flush calls within a single _start().
    match caller.data_mut().pending_flush.as_mut() {
        Some(existing) => existing.extend(pairs),
        None => caller.data_mut().pending_flush = Some(pairs),
    }
    caller.data_mut().completed = true;
}

fn log_handler(caller: &mut Caller<'_, WasmState>, ptr: i32) {
    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
    if let Ok(msg_bytes) = read_arraybuffer(&*caller, &memory, ptr) {
        let msg = String::from_utf8_lossy(&msg_bytes);
        let label = &caller.data().label;
        tracing::info!(indexer = %label, "{}", msg);
    }
}

fn abort_handler(caller: &mut Caller<'_, WasmState>, msg_ptr: i32, line: i32, col: i32) {
    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
    let msg = read_arraybuffer(&*caller, &memory, msg_ptr)
        .ok()
        .map(|b| String::from_utf8_lossy(&b).to_string())
        .unwrap_or_else(|| "<unreadable>".into());
    let label = caller.data().label.clone();
    tracing::error!(indexer = %label, line = line, col = col, "WASM abort: {}", msg);
    caller.data_mut().had_failure = true;
}

// ---------------------------------------------------------------------------
// ArrayBuffer helper
// ---------------------------------------------------------------------------

/// Read an AssemblyScript ArrayBuffer from WASM memory.
///
/// Layout: 4-byte LE length at `(ptr - 4)`, then `length` bytes at `ptr`.
fn read_arraybuffer(
    store: impl AsContext,
    memory: &Memory,
    ptr: i32,
) -> Result<Vec<u8>, String> {
    if ptr < 4 {
        return Err("invalid arraybuffer pointer".into());
    }

    let mem_data = memory.data(store.as_context());
    let len_offset = (ptr - 4) as usize;

    if len_offset + 4 > mem_data.len() {
        return Err("arraybuffer length out of bounds".into());
    }

    let len = u32::from_le_bytes([
        mem_data[len_offset],
        mem_data[len_offset + 1],
        mem_data[len_offset + 2],
        mem_data[len_offset + 3],
    ]) as usize;

    let data_offset = ptr as usize;
    if data_offset + len > mem_data.len() {
        return Err("arraybuffer data out of bounds".into());
    }

    Ok(mem_data[data_offset..data_offset + len].to_vec())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::IndexerStorage;
    use std::sync::Arc;

    fn temp_storage() -> (Arc<IndexerStorage>, tempfile::TempDir) {
        let dir = tempfile::tempdir().unwrap();
        let storage = Arc::new(IndexerStorage::open(dir.path()).unwrap());
        (storage, dir)
    }

    fn build_minimal_wasm() -> Vec<u8> {
        wat::parse_str(r#"
            (module
                (import "env" "__host_len" (func $host_len (result i32)))
                (import "env" "__load_input" (func $load_input (param i32)))
                (import "env" "__flush" (func $flush (param i32)))
                (import "env" "__log" (func $log (param i32)))
                (import "env" "__get" (func $get (param i32 i32)))
                (import "env" "__get_len" (func $get_len (param i32) (result i32)))
                (import "env" "abort" (func $abort (param i32 i32 i32 i32)))
                (memory (export "memory") 1)

                (func (export "_start")
                    (drop (call $host_len))
                    (i32.store (i32.const 96) (i32.const 0))
                    (call $flush (i32.const 100))
                )
            )
        "#).expect("failed to parse WAT")
    }

    fn build_view_wasm() -> Vec<u8> {
        wat::parse_str(r#"
            (module
                (import "env" "__host_len" (func $host_len (result i32)))
                (import "env" "__load_input" (func $load_input (param i32)))
                (import "env" "__flush" (func $flush (param i32)))
                (import "env" "__log" (func $log (param i32)))
                (import "env" "__get" (func $get (param i32 i32)))
                (import "env" "__get_len" (func $get_len (param i32) (result i32)))
                (import "env" "abort" (func $abort (param i32 i32 i32 i32)))
                (memory (export "memory") 1)

                (func (export "get_input_len") (result i32)
                    (i32.store (i32.const 200) (i32.const 4))
                    (i32.store (i32.const 204) (call $host_len))
                    (i32.const 204)
                )
            )
        "#).expect("failed to parse WAT")
    }

    #[test]
    fn test_compile_wasm() {
        let wasm = build_minimal_wasm();
        assert!(WasmIndexerRuntime::new(&wasm).is_ok());
    }

    #[test]
    fn test_compile_invalid_wasm() {
        assert!(WasmIndexerRuntime::new(b"not wasm").is_err());
    }

    #[test]
    fn test_run_block_minimal() {
        let wasm = build_minimal_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        let mut input = Vec::new();
        input.extend_from_slice(&100u32.to_le_bytes());
        input.extend_from_slice(b"fake_block_data");

        let result = runtime.run_block(input, storage, "test");
        assert!(result.is_ok());
        assert!(result.unwrap().is_empty());
    }

    #[test]
    fn test_call_view_sync() {
        let wasm = build_view_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        let result = runtime
            .call_view("get_input_len", b"hello".to_vec(), storage, "test")
            .unwrap();
        assert_eq!(result.len(), 4);
        let len = u32::from_le_bytes([result[0], result[1], result[2], result[3]]);
        assert_eq!(len, 5);
    }

    #[tokio::test]
    async fn test_call_view_async() {
        let wasm = build_view_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        let result = runtime
            .call_view_async("get_input_len", b"hello".to_vec(), storage, "test")
            .await
            .unwrap();
        assert_eq!(result.len(), 4);
        let len = u32::from_le_bytes([result[0], result[1], result[2], result[3]]);
        assert_eq!(len, 5);
    }

    #[test]
    fn test_call_view_missing_fn() {
        let wasm = build_minimal_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        let result = runtime.call_view("nonexistent", vec![], storage, "test");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("missing view fn"));
    }

    #[test]
    fn test_host_len_returns_input_size() {
        let wasm = build_view_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        for size in [0, 1, 100, 1000] {
            let input = vec![0u8; size];
            let result = runtime
                .call_view("get_input_len", input, storage.clone(), "test")
                .unwrap();
            let len = u32::from_le_bytes([result[0], result[1], result[2], result[3]]);
            assert_eq!(len as usize, size);
        }
    }

    /// Test the real alkanes WASM against a regtest genesis block.
        ///
        /// This catches storage format mismatches between qubitcoind's
        /// append_batch/get_latest and metashrew-runtime's SMT-backed store.
        ///
        /// The alkanes WASM processes the genesis block and calls __flush
        /// with KV pairs. We write them via append_batch and read them back
        /// via get_latest to verify round-trip correctness.
        #[test]
        fn test_alkanes_wasm_genesis_roundtrip() {
            let wasm_path = std::path::PathBuf::from(
                std::env::var("HOME").unwrap_or_else(|_| "/home/ubuntu".into()),
            )
            .join(".local/qubitcoin/indexers/alkanes/program.wasm");

            if !wasm_path.exists() {
                eprintln!("Skipping test: alkanes WASM not found at {:?}", wasm_path);
                return;
            }

            let wasm_bytes = std::fs::read(&wasm_path).unwrap();
            let runtime = WasmIndexerRuntime::new(&wasm_bytes).unwrap();
            let (storage, _dir) = temp_storage();

            // Build a minimal regtest genesis block.
            // The alkanes indexer processes the raw block bytes prefixed with height.
            // For the genesis block: height=0, block=regtest genesis hex.
            let genesis_hex = "0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4adae5494dffff7f20020000000101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff4d04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73ffffffff0100f2052a0100000043410496b538e853519c726a2c91e61ec11600ae1390813a627c66fb8be7947be63c52da7589379515d4e0a604f8141781e62294721166bf621e73a82cbf2342c858eeac00000000";
            let genesis_bytes: Vec<u8> = (0..genesis_hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&genesis_hex[i..i + 2], 16).unwrap())
                .collect();

            let height: u32 = 0;
            let mut input = Vec::with_capacity(4 + genesis_bytes.len());
            input.extend_from_slice(&height.to_le_bytes());
            input.extend_from_slice(&genesis_bytes);

            // Process block 0
            let pairs = runtime
                .run_block(input, Arc::clone(&storage), "alkanes")
                .expect("failed to process genesis block");

            assert!(!pairs.is_empty(), "genesis block should produce KV pairs");
            eprintln!("Genesis block produced {} KV pairs", pairs.len());

            // Write via append_batch (simulates run_indexer_block)
            storage
                .append_batch(&pairs, height)
                .expect("append_batch failed");

            // Read back every key via get_latest and verify round-trip
            let mut mismatches = 0;
            for (key, expected_value) in &pairs {
                match storage.get_latest(key) {
                    Some(actual_value) => {
                        if actual_value != *expected_value {
                            mismatches += 1;
                            if mismatches <= 3 {
                                eprintln!(
                                    "MISMATCH key={} expected_len={} actual_len={}",
                                    String::from_utf8_lossy(&key[..key.len().min(40)]),
                                    expected_value.len(),
                                    actual_value.len()
                                );
                            }
                        }
                    }
                    None => {
                        mismatches += 1;
                        if mismatches <= 3 {
                            eprintln!(
                                "MISSING key={} ({} bytes)",
                                String::from_utf8_lossy(&key[..key.len().min(40)]),
                                key.len()
                            );
                        }
                    }
                }
            }

            assert_eq!(
                mismatches, 0,
                "{} of {} keys failed round-trip through append_batch/get_latest",
                mismatches,
                pairs.len()
            );

            // Also verify tip_height was set
            assert_eq!(storage.tip_height(), 0, "tip should be 0 after genesis");

            // Now process a second empty block (height 1).
            // Build a minimal valid regtest block with only a coinbase.
            // Use height=1 and prev_hash from genesis.
            let height1: u32 = 1;
            let mut input1 = Vec::with_capacity(4 + genesis_bytes.len());
            input1.extend_from_slice(&height1.to_le_bytes());
            // Reuse genesis bytes (the WASM will process it as height 1)
            input1.extend_from_slice(&genesis_bytes);

            let pairs1 = runtime
                .run_block(input1, Arc::clone(&storage), "alkanes")
                .expect("failed to process block 1");

            eprintln!("Block 1 produced {} KV pairs", pairs1.len());

            storage
                .append_batch(&pairs1, height1)
                .expect("append_batch block 1 failed");

            // Verify all block 1 pairs round-trip
            let mut mismatches1 = 0;
            for (key, expected_value) in &pairs1 {
                match storage.get_latest(key) {
                    Some(actual_value) => {
                        if actual_value != *expected_value {
                            mismatches1 += 1;
                            if mismatches1 <= 3 {
                                eprintln!(
                                    "MISMATCH blk1 key={} expected_len={} actual_len={}",
                                    String::from_utf8_lossy(&key[..key.len().min(40)]),
                                    expected_value.len(),
                                    actual_value.len()
                                );
                            }
                        }
                    }
                    None => {
                        mismatches1 += 1;
                        if mismatches1 <= 3 {
                            eprintln!(
                                "MISSING blk1 key={}",
                                String::from_utf8_lossy(&key[..key.len().min(40)])
                            );
                        }
                    }
                }
            }

            assert_eq!(
                mismatches1, 0,
                "Block 1: {} of {} keys failed round-trip",
                mismatches1,
                pairs1.len()
            );

            // CRITICAL: verify block 0 keys are still readable after block 1
            let mut stale0 = 0;
            for (key, _) in &pairs {
                if storage.get_latest(key).is_none() {
                    stale0 += 1;
                    if stale0 <= 3 {
                        eprintln!(
                            "STALE blk0 key={}",
                            String::from_utf8_lossy(&key[..key.len().min(40)])
                        );
                    }
                }
            }

            assert_eq!(
                stale0, 0,
                "Block 0: {} of {} keys became unreadable after block 1",
                stale0,
                pairs.len()
            );

            assert_eq!(storage.tip_height(), 1, "tip should be 1 after block 1");
            eprintln!("All blocks verified: {} + {} pairs", pairs.len(), pairs1.len());
        }
}
