//! WASM indexer runtime using wasmtime.
//!
//! Implements the metashrew host ABI (6 host functions) and provides
//! `run_block()` for indexing and `call_view()` for read-only queries.

use crate::storage::IndexerStorage;
use prost::Message;
use std::sync::Arc;
use wasmtime::*;

/// Protobuf message for KeyValueFlush (generated by prost).
mod proto {
    include!(concat!(env!("OUT_DIR"), "/metashrew.rs"));
}

/// Host state threaded through the wasmtime `Store`.
pub struct WasmState {
    /// Input data: `[height_le32 ++ block_data]`.
    pub input_data: Vec<u8>,
    /// Pending key-value pairs from `__flush`.
    pub pending_flush: Option<Vec<(Vec<u8>, Vec<u8>)>>,
    /// Reference to the indexer's storage.
    pub storage: Arc<IndexerStorage>,
    /// Whether the WASM module hit an error (abort).
    pub had_failure: bool,
    /// Whether `__flush` was called (module completed successfully).
    pub completed: bool,
    /// Label for logging.
    pub label: String,
    /// Whether this is a view-only call (no-op flush).
    pub view_mode: bool,
    /// Resource limits (matching metashrew State).
    pub limits: StoreLimits,
}

/// A compiled WASM indexer runtime.
pub struct WasmIndexerRuntime {
    engine: Engine,
    module: Module,
}

impl WasmIndexerRuntime {
    /// Compile a WASM module from bytes.
    pub fn new(wasm_bytes: &[u8]) -> Result<Self, String> {
        let mut config = Config::new();
        // Match metashrew-runtime engine config for deterministic execution.
        config.wasm_bulk_memory(true);
        config.wasm_multi_value(true);
        config.wasm_reference_types(true);
        config.wasm_simd(true);
        config.cranelift_nan_canonicalization(true);
        config.relaxed_simd_deterministic(true);
        config.static_memory_maximum_size(0x100000000); // 4GB
        config.static_memory_guard_size(0x10000); // 64KB
        config.memory_init_cow(false);

        let engine = Engine::new(&config).map_err(|e| format!("wasmtime engine: {}", e))?;
        let module =
            Module::new(&engine, wasm_bytes).map_err(|e| format!("wasmtime compile: {}", e))?;

        Ok(WasmIndexerRuntime { engine, module })
    }

    /// Run `_start()` on the WASM module with the given block data.
    ///
    /// `input_data` is `[height_le32 ++ serialized_block]`.
    pub fn run_block(
        &self,
        input_data: Vec<u8>,
        storage: Arc<IndexerStorage>,
        label: &str,
    ) -> Result<Vec<(Vec<u8>, Vec<u8>)>, String> {
        let state = WasmState {
            input_data,
            pending_flush: None,
            storage,
            had_failure: false,
            completed: false,
            label: label.to_string(),
            view_mode: false,
            limits: StoreLimitsBuilder::new()
                .memories(usize::MAX)
                .tables(usize::MAX)
                .instances(usize::MAX)
                .build(),
        };

        let mut store = Store::new(&self.engine, state);
        store.limiter(|s| &mut s.limits);
        let instance = self.instantiate(&mut store)?;

        // Grow memory to max for deterministic execution (matching metashrew).
        if let Some(memory) = instance.get_memory(&mut store, "memory") {
            let current = memory.size(&store);
            let max_pages: u64 = 65536; // 4GB
            let to_grow = max_pages.saturating_sub(current);
            if to_grow > 0 {
                let _ = memory.grow(&mut store, to_grow);
            }
        }

        // Call _start
        let start_fn = instance
            .get_typed_func::<(), ()>(&mut store, "_start")
            .map_err(|e| format!("missing _start: {}", e))?;

        start_fn
            .call(&mut store, ())
            .map_err(|e| format!("_start failed: {}", e))?;

        let state = store.into_data();
        if state.had_failure {
            return Err("WASM module aborted".into());
        }
        if !state.completed {
            return Err("WASM module did not call __flush".into());
        }

        Ok(state.pending_flush.unwrap_or_default())
    }

    /// Call a view function on the WASM module.
    ///
    /// Creates a fresh instance in view mode (no-op flush) and calls the
    /// named export with `input_data` available via `__host_len`/`__load_input`.
    /// Returns the bytes written to the output buffer via `__flush`.
    pub fn call_view(
        &self,
        fn_name: &str,
        input_data: Vec<u8>,
        storage: Arc<IndexerStorage>,
        label: &str,
    ) -> Result<Vec<u8>, String> {
        let state = WasmState {
            input_data,
            pending_flush: None,
            storage,
            had_failure: false,
            completed: false,
            label: label.to_string(),
            view_mode: true,
            limits: StoreLimitsBuilder::new()
                .memories(usize::MAX)
                .tables(usize::MAX)
                .instances(usize::MAX)
                .build(),
        };

        let mut store = Store::new(&self.engine, state);
        store.limiter(|s| &mut s.limits);
        let instance = self.instantiate(&mut store)?;

        // Grow memory to max for deterministic execution.
        if let Some(memory) = instance.get_memory(&mut store, "memory") {
            let current = memory.size(&store);
            let max_pages: u64 = 65536;
            let to_grow = max_pages.saturating_sub(current);
            if to_grow > 0 {
                let _ = memory.grow(&mut store, to_grow);
            }
        }

        // Call the view function — it returns an i32 pointer to the result.
        let view_fn = instance
            .get_typed_func::<(), i32>(&mut store, fn_name)
            .map_err(|e| format!("missing view fn '{}': {}", fn_name, e))?;

        let result_ptr = view_fn
            .call(&mut store, ())
            .map_err(|e| format!("view fn '{}' failed: {}", fn_name, e))?;

        // Read the result from WASM memory using AssemblyScript ArrayBuffer layout.
        let memory = instance
            .get_memory(&mut store, "memory")
            .ok_or("no memory export")?;

        let result = read_arraybuffer(&store, &memory, result_ptr)?;
        Ok(result)
    }

    /// Create an instance with all host functions linked.
    fn instantiate(&self, store: &mut Store<WasmState>) -> Result<Instance, String> {
        let mut linker = Linker::new(&self.engine);

        // __host_len() -> i32
        linker
            .func_wrap("env", "__host_len", |caller: Caller<'_, WasmState>| -> i32 {
                caller.data().input_data.len() as i32
            })
            .map_err(|e| format!("link __host_len: {}", e))?;

        // __load_input(ptr: i32)
        linker
            .func_wrap(
                "env",
                "__load_input",
                |mut caller: Caller<'_, WasmState>, ptr: i32| {
                    let data = caller.data().input_data.clone();
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    memory.write(&mut caller, ptr as usize, &data).ok();
                },
            )
            .map_err(|e| format!("link __load_input: {}", e))?;

        // __get_len(key_ptr: i32) -> i32
        linker
            .func_wrap(
                "env",
                "__get_len",
                |mut caller: Caller<'_, WasmState>, key_ptr: i32| -> i32 {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    let key = match read_arraybuffer(&caller, &memory, key_ptr) {
                        Ok(k) => k,
                        Err(_) => return 0,
                    };
                    let storage = &caller.data().storage;
                    match storage.get_latest(&key) {
                        Some(v) => v.len() as i32,
                        None => 0,
                    }
                },
            )
            .map_err(|e| format!("link __get_len: {}", e))?;

        // __get(key_ptr: i32, value_ptr: i32)
        linker
            .func_wrap(
                "env",
                "__get",
                |mut caller: Caller<'_, WasmState>, key_ptr: i32, value_ptr: i32| {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    let key = match read_arraybuffer(&caller, &memory, key_ptr) {
                        Ok(k) => k,
                        Err(_) => return,
                    };
                    let storage = &caller.data().storage;
                    if let Some(value) = storage.get_latest(&key) {
                        memory.write(&mut caller, value_ptr as usize, &value).ok();
                    }
                },
            )
            .map_err(|e| format!("link __get: {}", e))?;

        // __flush(data_ptr: i32)
        linker
            .func_wrap(
                "env",
                "__flush",
                |mut caller: Caller<'_, WasmState>, data_ptr: i32| {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    let data = match read_arraybuffer(&caller, &memory, data_ptr) {
                        Ok(d) => d,
                        Err(e) => {
                            tracing::error!(error = %e, "failed to read __flush data");
                            caller.data_mut().had_failure = true;
                            return;
                        }
                    };

                    // Decode protobuf KeyValueFlush.
                    let flush_msg = match proto::KeyValueFlush::decode(data.as_slice()) {
                        Ok(m) => m,
                        Err(e) => {
                            tracing::error!(error = %e, "failed to decode KeyValueFlush");
                            caller.data_mut().had_failure = true;
                            return;
                        }
                    };

                    // Parse key-value pairs from the list (alternating key, value).
                    let mut pairs = Vec::new();
                    let list = &flush_msg.list;
                    let mut i = 0;
                    while i + 1 < list.len() {
                        pairs.push((list[i].to_vec(), list[i + 1].to_vec()));
                        i += 2;
                    }

                    caller.data_mut().pending_flush = Some(pairs);
                    caller.data_mut().completed = true;
                },
            )
            .map_err(|e| format!("link __flush: {}", e))?;

        // __log(ptr: i32)
        linker
            .func_wrap(
                "env",
                "__log",
                |mut caller: Caller<'_, WasmState>, ptr: i32| {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    if let Ok(msg_bytes) = read_arraybuffer(&caller, &memory, ptr) {
                        let msg = String::from_utf8_lossy(&msg_bytes);
                        let label = &caller.data().label;
                        tracing::info!(indexer = %label, "{}", msg);
                    }
                },
            )
            .map_err(|e| format!("link __log: {}", e))?;

        // abort(msg: i32, file: i32, line: i32, col: i32)
        linker
            .func_wrap(
                "env",
                "abort",
                |mut caller: Caller<'_, WasmState>,
                 msg_ptr: i32,
                 _file_ptr: i32,
                 line: i32,
                 col: i32| {
                    let memory = caller.get_export("memory").unwrap().into_memory().unwrap();
                    let msg = read_arraybuffer(&caller, &memory, msg_ptr)
                        .ok()
                        .map(|b| String::from_utf8_lossy(&b).to_string())
                        .unwrap_or_else(|| "<unreadable>".into());
                    let label = caller.data().label.clone();
                    tracing::error!(
                        indexer = %label,
                        line = line,
                        col = col,
                        "WASM abort: {}",
                        msg
                    );
                    caller.data_mut().had_failure = true;
                },
            )
            .map_err(|e| format!("link abort: {}", e))?;

        // Stub any remaining unknown imports (e.g. wasm-bindgen placeholders)
        // as traps so modules that include unused wasm-bindgen glue still load.
        linker
            .define_unknown_imports_as_traps(&self.module)
            .map_err(|e| format!("define unknown imports: {}", e))?;

        linker
            .instantiate(&mut *store, &self.module)
            .map_err(|e| format!("wasmtime instantiate: {}", e))
    }
}

/// Read an AssemblyScript ArrayBuffer from WASM memory.
///
/// Layout: 4-byte LE length at `(ptr - 4)`, then `length` bytes at `ptr`.
fn read_arraybuffer(
    store: impl AsContext,
    memory: &Memory,
    ptr: i32,
) -> Result<Vec<u8>, String> {
    if ptr < 4 {
        return Err("invalid arraybuffer pointer".into());
    }

    let mem_data = memory.data(store.as_context());
    let len_offset = (ptr - 4) as usize;

    if len_offset + 4 > mem_data.len() {
        return Err("arraybuffer length out of bounds".into());
    }

    let len = u32::from_le_bytes([
        mem_data[len_offset],
        mem_data[len_offset + 1],
        mem_data[len_offset + 2],
        mem_data[len_offset + 3],
    ]) as usize;

    let data_offset = ptr as usize;
    if data_offset + len > mem_data.len() {
        return Err("arraybuffer data out of bounds".into());
    }

    Ok(mem_data[data_offset..data_offset + len].to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::IndexerStorage;
    use std::sync::Arc;

    fn temp_storage() -> (Arc<IndexerStorage>, tempfile::TempDir) {
        let dir = tempfile::tempdir().unwrap();
        let storage = Arc::new(IndexerStorage::open(dir.path()).unwrap());
        (storage, dir)
    }

    /// Build a minimal WASM module that:
    /// 1. Calls __host_len to get input size
    /// 2. Calls __flush with an empty protobuf (just sets completed=true)
    ///
    /// The module creates a zero-length KeyValueFlush protobuf at memory offset 100,
    /// with the ArrayBuffer length prefix at offset 96.
    fn build_minimal_wasm() -> Vec<u8> {
        wat::parse_str(r#"
            (module
                (import "env" "__host_len" (func $host_len (result i32)))
                (import "env" "__load_input" (func $load_input (param i32)))
                (import "env" "__flush" (func $flush (param i32)))
                (import "env" "__log" (func $log (param i32)))
                (import "env" "__get" (func $get (param i32 i32)))
                (import "env" "__get_len" (func $get_len (param i32) (result i32)))
                (import "env" "abort" (func $abort (param i32 i32 i32 i32)))
                (memory (export "memory") 1)

                (func (export "_start")
                    ;; Get input length (just to exercise __host_len).
                    (drop (call $host_len))

                    ;; Build an empty protobuf KeyValueFlush at memory offset 100.
                    ;; ArrayBuffer layout: [length_u32_le @ offset 96][data @ offset 100]
                    ;; Empty protobuf = 0 bytes.
                    (i32.store (i32.const 96) (i32.const 0))

                    ;; Call __flush with ptr=100 (the data starts here, length at 96).
                    (call $flush (i32.const 100))
                )
            )
        "#).expect("failed to parse WAT")
    }

    /// Build a WASM module that calls __host_len and returns it as a view result.
    fn build_view_wasm() -> Vec<u8> {
        wat::parse_str(r#"
            (module
                (import "env" "__host_len" (func $host_len (result i32)))
                (import "env" "__load_input" (func $load_input (param i32)))
                (import "env" "__flush" (func $flush (param i32)))
                (import "env" "__log" (func $log (param i32)))
                (import "env" "__get" (func $get (param i32 i32)))
                (import "env" "__get_len" (func $get_len (param i32) (result i32)))
                (import "env" "abort" (func $abort (param i32 i32 i32 i32)))
                (memory (export "memory") 1)

                (func (export "get_input_len") (result i32)
                    ;; Store the input length as a 4-byte LE value at offset 204.
                    ;; ArrayBuffer: length at 200, data at 204.
                    (i32.store (i32.const 200) (i32.const 4))
                    (i32.store (i32.const 204) (call $host_len))

                    ;; Return pointer to the data (204).
                    (i32.const 204)
                )
            )
        "#).expect("failed to parse WAT")
    }

    #[test]
    fn test_compile_wasm() {
        let wasm = build_minimal_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm);
        assert!(runtime.is_ok());
    }

    #[test]
    fn test_compile_invalid_wasm() {
        let result = WasmIndexerRuntime::new(b"not wasm");
        assert!(result.is_err());
    }

    #[test]
    fn test_run_block_minimal() {
        let wasm = build_minimal_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        // Build input: height=100 + empty block data.
        let mut input = Vec::new();
        input.extend_from_slice(&100u32.to_le_bytes());
        input.extend_from_slice(b"fake_block_data");

        let result = runtime.run_block(input, storage, "test");
        assert!(result.is_ok());
        let pairs = result.unwrap();
        // Empty flush = no key-value pairs.
        assert!(pairs.is_empty());
    }

    #[test]
    fn test_call_view() {
        let wasm = build_view_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        let input = b"hello".to_vec();
        let result = runtime.call_view("get_input_len", input.clone(), storage, "test");
        assert!(result.is_ok());

        let output = result.unwrap();
        // Output should be 4 bytes (u32 LE) containing the input length (5).
        assert_eq!(output.len(), 4);
        let len = u32::from_le_bytes([output[0], output[1], output[2], output[3]]);
        assert_eq!(len, 5);
    }

    #[test]
    fn test_call_view_missing_fn() {
        let wasm = build_minimal_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        let result = runtime.call_view("nonexistent", vec![], storage, "test");
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("missing view fn"));
    }

    #[test]
    fn test_host_len_returns_input_size() {
        let wasm = build_view_wasm();
        let runtime = WasmIndexerRuntime::new(&wasm).unwrap();
        let (storage, _dir) = temp_storage();

        // Test with different input sizes.
        for size in [0, 1, 100, 1000] {
            let input = vec![0u8; size];
            let result = runtime
                .call_view("get_input_len", input, storage.clone(), "test")
                .unwrap();
            let len = u32::from_le_bytes([result[0], result[1], result[2], result[3]]);
            assert_eq!(len as usize, size);
        }
    }
}
