[package]
name = "qubitcoin-wallet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Wallet implementation for Qubitcoin: descriptor wallet, coin selection, PSBT"

[dependencies]
qubitcoin-common = { workspace = true }
qubitcoin-node = { workspace = true }
qubitcoin-util = { workspace = true }
qubitcoin-primitives = { workspace = true }
qubitcoin-crypto = { workspace = true }
qubitcoin-consensus = { workspace = true }
qubitcoin-script = { workspace = true }
qubitcoin-serialize = { workspace = true }
thiserror = { workspace = true }
secp256k1 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
