//! Shared indexer traits and state layout for Qubitcoin secondary indexers.
//!
//! This crate provides the target-agnostic building blocks shared by both
//! the native (wasmtime + RocksDB) and web (js-sys + HashMap) indexer adapters.

pub mod rollback;
pub mod smt;
pub mod state;
pub mod traits;

/// Protobuf message for KeyValueFlush (generated by prost).
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/metashrew.rs"));
}
