//! Core wallet structure for Qubitcoin descriptor wallets.
//!
//! Maps to: `src/wallet/wallet.h` and `src/wallet/wallet.cpp` in Bitcoin Core.
//!
//! Provides:
//! - [`DerivationPath`]: BIP32 HD derivation path.
//! - [`DescriptorType`]: Output descriptor type (P2PKH, P2WPKH, P2SH-P2WPKH, P2TR).
//! - [`WalletKey`]: A key with derivation metadata.
//! - [`AddressInfo`]: An address generated by the wallet.
//! - [`Wallet`]: The descriptor wallet managing keys, addresses, transactions, and UTXOs.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use qubitcoin_common::keys::{Key, PubKey, XOnlyPubKey};
use qubitcoin_consensus::transaction::{OutPoint, TransactionRef, TxOut};
use qubitcoin_crypto::hash::hash160;
use qubitcoin_primitives::{Amount, Txid};
use qubitcoin_script::{build_p2pkh, build_p2sh, build_p2tr, build_p2wpkh, Script};

// ---------------------------------------------------------------------------
// DerivationPath
// ---------------------------------------------------------------------------

/// HD derivation path (BIP32).
///
/// Stores the path components as a `Vec<u32>`. Hardened indices have the
/// top bit set (`0x8000_0000`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DerivationPath(Vec<u32>);

/// Hardened derivation flag -- added to the child index.
const HARDENED: u32 = 0x8000_0000;

impl DerivationPath {
    /// Create a derivation path from raw components.
    pub fn new(path: Vec<u32>) -> Self {
        DerivationPath(path)
    }

    /// Build a BIP-44 path: `m/44'/coin'/account'/change/index`.
    pub fn bip44(coin_type: u32, account: u32, change: u32, index: u32) -> Self {
        DerivationPath(vec![
            44 | HARDENED,
            coin_type | HARDENED,
            account | HARDENED,
            change,
            index,
        ])
    }

    /// Build a BIP-84 path: `m/84'/coin'/account'/change/index`.
    pub fn bip84(coin_type: u32, account: u32, change: u32, index: u32) -> Self {
        DerivationPath(vec![
            84 | HARDENED,
            coin_type | HARDENED,
            account | HARDENED,
            change,
            index,
        ])
    }

    /// Build a BIP-86 path: `m/86'/coin'/account'/change/index`.
    pub fn bip86(coin_type: u32, account: u32, change: u32, index: u32) -> Self {
        DerivationPath(vec![
            86 | HARDENED,
            coin_type | HARDENED,
            account | HARDENED,
            change,
            index,
        ])
    }

    /// Number of path components.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Whether the path is empty.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Borrow the path components as a slice.
    pub fn as_slice(&self) -> &[u32] {
        &self.0
    }
}

impl std::fmt::Display for DerivationPath {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "m")?;
        for &idx in &self.0 {
            if idx & HARDENED != 0 {
                write!(f, "/{}'", idx & !HARDENED)?;
            } else {
                write!(f, "/{}", idx)?;
            }
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// DescriptorType
// ---------------------------------------------------------------------------

/// Output descriptor type, selecting the script template used for addresses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DescriptorType {
    /// P2PKH -- pay-to-public-key-hash (legacy).
    Pkh,
    /// P2WPKH -- native SegWit (bech32).
    Wpkh,
    /// P2SH-P2WPKH -- wrapped SegWit (3-prefix on mainnet).
    ShWpkh,
    /// P2TR -- Taproot (bech32m).
    Tr,
}

// ---------------------------------------------------------------------------
// WalletKey
// ---------------------------------------------------------------------------

/// A wallet key together with its derivation metadata.
#[derive(Debug, Clone)]
pub struct WalletKey {
    /// The private key.
    pub key: Key,
    /// The corresponding public key.
    pub pubkey: PubKey,
    /// Derivation path used to produce this key.
    pub path: DerivationPath,
    /// Descriptor type associated with this key.
    pub descriptor_type: DescriptorType,
}

// ---------------------------------------------------------------------------
// AddressInfo
// ---------------------------------------------------------------------------

/// Metadata about a generated address.
#[derive(Debug, Clone)]
pub struct AddressInfo {
    /// The human-readable encoded address (hex of the scriptPubKey for now).
    pub address: String,
    /// The scriptPubKey locking funds to this address.
    pub script_pubkey: Script,
    /// Index of the corresponding key in the wallet's key pool.
    pub key_index: usize,
    /// Whether this is a change address.
    pub is_change: bool,
}

// ---------------------------------------------------------------------------
// WalletTx / WalletUtxo
// ---------------------------------------------------------------------------

/// A transaction tracked by the wallet.
#[derive(Debug, Clone)]
pub struct WalletTx {
    /// The transaction itself (shared reference).
    pub tx: TransactionRef,
    /// Block height if confirmed, `None` if still in the mempool.
    pub height: Option<i32>,
    /// Unix timestamp when the wallet first saw this transaction.
    pub time: u64,
}

/// An unspent transaction output owned by the wallet.
#[derive(Debug, Clone)]
pub struct WalletUtxo {
    /// The outpoint identifying this UTXO.
    pub outpoint: OutPoint,
    /// The output data (value + scriptPubKey).
    pub tx_out: TxOut,
    /// Block height if confirmed, `None` if in the mempool.
    pub height: Option<i32>,
    /// Whether this UTXO belongs to a change address.
    pub is_change: bool,
}

// ---------------------------------------------------------------------------
// Wallet
// ---------------------------------------------------------------------------

/// The descriptor wallet.
///
/// Manages a set of keys, addresses (receiving and change), transactions, and
/// unspent outputs. This is a simplified in-memory wallet inspired by Bitcoin
/// Core's descriptor wallet architecture.
pub struct Wallet {
    name: String,
    keys: Vec<WalletKey>,
    addresses: Vec<AddressInfo>,
    change_addresses: Vec<AddressInfo>,
    next_key_index: usize,
    next_change_index: usize,
    descriptor_type: DescriptorType,
    /// Transactions relevant to this wallet, keyed by txid.
    transactions: HashMap<Txid, WalletTx>,
    /// Unspent outputs owned by this wallet.
    unspent: HashMap<OutPoint, WalletUtxo>,
}

impl Wallet {
    /// Create a new, empty wallet with the given name and descriptor type.
    pub fn new(name: &str, descriptor_type: DescriptorType) -> Self {
        Wallet {
            name: name.to_string(),
            keys: Vec::new(),
            addresses: Vec::new(),
            change_addresses: Vec::new(),
            next_key_index: 0,
            next_change_index: 0,
            descriptor_type,
            transactions: HashMap::new(),
            unspent: HashMap::new(),
        }
    }

    /// The wallet name.
    pub fn name(&self) -> &str {
        &self.name
    }

    /// The descriptor type this wallet uses for address generation.
    pub fn descriptor_type(&self) -> DescriptorType {
        self.descriptor_type
    }

    // -- Key / address generation -------------------------------------------

    /// Generate a new receiving address, appending a fresh key to the pool.
    pub fn get_new_address(&mut self) -> AddressInfo {
        let index = self.next_key_index;
        self.next_key_index += 1;

        let (wk, addr_info) = self.generate_key_and_address(index, false);
        self.keys.push(wk);
        self.addresses.push(addr_info.clone());
        addr_info
    }

    /// Generate a new change address, appending a fresh key to the pool.
    pub fn get_change_address(&mut self) -> AddressInfo {
        let index = self.next_change_index;
        self.next_change_index += 1;

        let (wk, addr_info) = self.generate_key_and_address(index, true);
        self.keys.push(wk);
        self.change_addresses.push(addr_info.clone());
        addr_info
    }

    // -- Balance / UTXO queries ---------------------------------------------

    /// Total confirmed + unconfirmed balance (sum of all UTXOs).
    pub fn get_balance(&self) -> Amount {
        self.unspent
            .values()
            .fold(Amount::ZERO, |acc, utxo| acc + utxo.tx_out.value)
    }

    /// Return references to all unspent outputs.
    pub fn list_unspent(&self) -> Vec<&WalletUtxo> {
        self.unspent.values().collect()
    }

    // -- Transaction tracking -----------------------------------------------

    /// Record a transaction and update the UTXO set.
    ///
    /// * Scans outputs -- any output whose scriptPubKey matches a wallet
    ///   address is added to the UTXO set.
    /// * Scans inputs -- any input that spends a wallet UTXO removes it.
    pub fn add_transaction(&mut self, tx: TransactionRef, height: Option<i32>) {
        let txid = *tx.txid();
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        // Record the transaction itself.
        self.transactions.insert(
            txid,
            WalletTx {
                tx: Arc::clone(&tx),
                height,
                time: now,
            },
        );

        // Remove spent UTXOs.
        for input in &tx.vin {
            self.unspent.remove(&input.prevout);
        }

        // Add new UTXOs that pay to our addresses.
        for (vout_idx, output) in tx.vout.iter().enumerate() {
            let is_ours = self.is_mine(&output.script_pubkey);
            if let Some(is_change) = is_ours {
                let outpoint = OutPoint::new(txid, vout_idx as u32);
                self.unspent.insert(
                    outpoint.clone(),
                    WalletUtxo {
                        outpoint,
                        tx_out: output.clone(),
                        height,
                        is_change,
                    },
                );
            }
        }
    }

    /// Look up a wallet transaction by txid.
    pub fn get_transaction(&self, txid: &Txid) -> Option<&WalletTx> {
        self.transactions.get(txid)
    }

    /// Return references to all tracked transactions.
    pub fn list_transactions(&self) -> Vec<&WalletTx> {
        self.transactions.values().collect()
    }

    // -- Internal helpers ---------------------------------------------------

    /// Check whether `script_pubkey` matches one of the wallet's addresses.
    /// Returns `Some(is_change)` if it matches, `None` otherwise.
    fn is_mine(&self, script_pubkey: &Script) -> Option<bool> {
        for addr in &self.addresses {
            if addr.script_pubkey == *script_pubkey {
                return Some(false);
            }
        }
        for addr in &self.change_addresses {
            if addr.script_pubkey == *script_pubkey {
                return Some(true);
            }
        }
        None
    }

    /// Generate a fresh key and the corresponding address info.
    fn generate_key_and_address(&self, index: usize, is_change: bool) -> (WalletKey, AddressInfo) {
        let key = Key::generate();
        let pubkey = key.get_pubkey();

        let change_flag: u32 = if is_change { 1 } else { 0 };

        let (path, script_pubkey) = match self.descriptor_type {
            DescriptorType::Pkh => {
                let path = DerivationPath::bip44(0, 0, change_flag, index as u32);
                let script = build_p2pkh(&pubkey.get_id());
                (path, script)
            }
            DescriptorType::Wpkh => {
                let path = DerivationPath::bip84(0, 0, change_flag, index as u32);
                let script = build_p2wpkh(&pubkey.get_id());
                (path, script)
            }
            DescriptorType::ShWpkh => {
                let path = DerivationPath::bip84(0, 0, change_flag, index as u32);
                // Inner witness program: OP_0 <20-byte-hash>
                let inner = build_p2wpkh(&pubkey.get_id());
                let inner_hash = hash160(inner.as_bytes());
                let script = build_p2sh(&inner_hash);
                (path, script)
            }
            DescriptorType::Tr => {
                let path = DerivationPath::bip86(0, 0, change_flag, index as u32);
                let xonly = XOnlyPubKey::from_pubkey(&pubkey);
                let script = build_p2tr(&xonly.serialize());
                (path, script)
            }
        };

        // Produce a hex-encoded "address" from the scriptPubKey.
        let address = hex::encode(script_pubkey.as_bytes());

        let key_index = self.keys.len(); // will be appended right after

        let wk = WalletKey {
            key,
            pubkey,
            path,
            descriptor_type: self.descriptor_type,
        };

        let addr_info = AddressInfo {
            address,
            script_pubkey,
            key_index,
            is_change,
        };

        (wk, addr_info)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use qubitcoin_consensus::transaction::{Transaction, TxIn, TxOut};
    use qubitcoin_primitives::Amount;

    /// Helper: create a simple coinbase-like transaction paying to the given
    /// scriptPubKey with the specified amount.
    fn make_funding_tx(script_pubkey: Script, value: Amount) -> TransactionRef {
        let input = TxIn::coinbase(Script::from_bytes(vec![0x04, 0xff]));
        let output = TxOut::new(value, script_pubkey);
        Arc::new(Transaction::new(2, vec![input], vec![output], 0))
    }

    #[test]
    fn test_create_wallet() {
        let wallet = Wallet::new("test_wallet", DescriptorType::Wpkh);
        assert_eq!(wallet.name(), "test_wallet");
        assert_eq!(wallet.descriptor_type(), DescriptorType::Wpkh);
        assert_eq!(wallet.get_balance(), Amount::ZERO);
        assert!(wallet.list_unspent().is_empty());
        assert!(wallet.list_transactions().is_empty());
    }

    #[test]
    fn test_generate_addresses_wpkh() {
        let mut wallet = Wallet::new("w", DescriptorType::Wpkh);
        let a1 = wallet.get_new_address();
        let a2 = wallet.get_new_address();

        // Addresses should be distinct.
        assert_ne!(a1.address, a2.address);
        assert!(!a1.is_change);
        assert!(!a2.is_change);

        // ScriptPubKey should be a valid P2WPKH (22 bytes).
        assert!(a1.script_pubkey.is_p2wpkh());
        assert!(a2.script_pubkey.is_p2wpkh());
    }

    #[test]
    fn test_generate_change_address() {
        let mut wallet = Wallet::new("w", DescriptorType::Wpkh);
        let ca = wallet.get_change_address();
        assert!(ca.is_change);
        assert!(ca.script_pubkey.is_p2wpkh());
    }

    #[test]
    fn test_generate_addresses_pkh() {
        let mut wallet = Wallet::new("w", DescriptorType::Pkh);
        let a = wallet.get_new_address();
        assert!(a.script_pubkey.is_p2pkh());
    }

    #[test]
    fn test_generate_addresses_sh_wpkh() {
        let mut wallet = Wallet::new("w", DescriptorType::ShWpkh);
        let a = wallet.get_new_address();
        assert!(a.script_pubkey.is_p2sh());
    }

    #[test]
    fn test_generate_addresses_tr() {
        let mut wallet = Wallet::new("w", DescriptorType::Tr);
        let a = wallet.get_new_address();
        assert!(a.script_pubkey.is_p2tr());
    }

    #[test]
    fn test_add_transaction_and_balance() {
        let mut wallet = Wallet::new("w", DescriptorType::Wpkh);
        let addr = wallet.get_new_address();

        let funding_tx = make_funding_tx(addr.script_pubkey.clone(), Amount::from_sat(100_000));
        wallet.add_transaction(funding_tx.clone(), Some(100));

        assert_eq!(wallet.get_balance(), Amount::from_sat(100_000));
        assert_eq!(wallet.list_unspent().len(), 1);
        assert_eq!(wallet.list_transactions().len(), 1);

        let wtx = wallet.get_transaction(funding_tx.txid()).unwrap();
        assert_eq!(wtx.height, Some(100));
    }

    #[test]
    fn test_spending_removes_utxo() {
        let mut wallet = Wallet::new("w", DescriptorType::Wpkh);
        let addr = wallet.get_new_address();

        // Fund the wallet.
        let funding_tx = make_funding_tx(addr.script_pubkey.clone(), Amount::from_sat(50_000));
        wallet.add_transaction(funding_tx.clone(), Some(1));
        assert_eq!(wallet.get_balance(), Amount::from_sat(50_000));

        // Spend the UTXO (output goes to an external address, so balance drops to zero).
        let spend_input = TxIn::new(
            OutPoint::new(*funding_tx.txid(), 0),
            Script::new(),
            0xFFFFFFFF,
        );
        let mut external_spk = vec![0x00, 0x14];
        external_spk.extend_from_slice(&[0xab; 20]);
        let external_output =
            TxOut::new(Amount::from_sat(49_000), Script::from_bytes(external_spk));
        let spend_tx = Arc::new(Transaction::new(
            2,
            vec![spend_input],
            vec![external_output],
            0,
        ));
        wallet.add_transaction(spend_tx, Some(2));

        assert_eq!(wallet.get_balance(), Amount::ZERO);
        assert!(wallet.list_unspent().is_empty());
    }

    #[test]
    fn test_derivation_path_display() {
        let path = DerivationPath::bip84(0, 0, 0, 5);
        assert_eq!(format!("{}", path), "m/84'/0'/0'/0/5");

        let path = DerivationPath::bip44(1, 2, 1, 10);
        assert_eq!(format!("{}", path), "m/44'/1'/2'/1/10");

        let path = DerivationPath::bip86(0, 0, 0, 0);
        assert_eq!(format!("{}", path), "m/86'/0'/0'/0/0");
    }

    #[test]
    fn test_derivation_path_basic() {
        let path = DerivationPath::new(vec![44 | HARDENED, 0, 1]);
        assert_eq!(path.len(), 3);
        assert!(!path.is_empty());
        assert_eq!(path.as_slice()[0], 44 | HARDENED);
    }

    #[test]
    fn test_multiple_funding_transactions() {
        let mut wallet = Wallet::new("w", DescriptorType::Wpkh);
        let a1 = wallet.get_new_address();
        let a2 = wallet.get_new_address();

        let tx1 = make_funding_tx(a1.script_pubkey.clone(), Amount::from_sat(10_000));
        let tx2 = make_funding_tx(a2.script_pubkey.clone(), Amount::from_sat(20_000));

        wallet.add_transaction(tx1, Some(10));
        wallet.add_transaction(tx2, Some(11));

        assert_eq!(wallet.get_balance(), Amount::from_sat(30_000));
        assert_eq!(wallet.list_unspent().len(), 2);
        assert_eq!(wallet.list_transactions().len(), 2);
    }
}
