[package]
name = "qubitcoind"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Qubitcoin daemon: full node implementation"

[[bin]]
name = "qubitcoind"
path = "src/main.rs"

[dependencies]
qubitcoin-util = { workspace = true, features = ["native"] }
qubitcoin-common = { workspace = true, features = ["native"] }
qubitcoin-consensus = { workspace = true }
qubitcoin-primitives = { workspace = true }
qubitcoin-node = { workspace = true, features = ["filesystem", "parallel"] }
qubitcoin-net = { workspace = true }
qubitcoin-rpc = { workspace = true }
qubitcoin-storage = { workspace = true, features = ["rocksdb-backend"] }
qubitcoin-script = { workspace = true }
qubitcoin-serialize = { workspace = true }
qubitcoin-wallet = { workspace = true }
qubitcoin-indexer = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
