[package]
name = "qubitcoin-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Utility functions for Qubitcoin: logging, time, fs, args, thread names"

[dependencies]
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
